name: Deploy to Heroku

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          justlogin: true

      - name: Deploy to Heroku
        run: |
          git fetch --unshallow
          git push -f https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git HEAD:refs/heads/main
      
      - name: Verify Deployment
        run: |
          echo "✅ Deployed to Heroku successfully"
          echo "🔗 https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com"
          echo "NOTE: You still need to manually upload authentication credentials!"